buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.3.0"
    }
}

plugins {
    id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
    id 'com.android.application' version '8.3.0' apply false
}

allprojects {
    // Repositories are defined in settings.gradle (FAIL_ON_PROJECT_REPOS)
}

task clean(type: Delete) {
    delete rootProject.buildDir
}